# Generated by Django 5.0.3 on 2024-04-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='log date')),
                ('rarity', models.CharField(choices=[('N', 'New'), ('P', 'Previously Owned'), ('M', 'Multiple Owners')], default='N', max_length=30)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shoe')),
            ],
            options={
                'ordering': ['-rarity'],
            },
        ),
    ]
