# Generated by Django 5.0.3 on 2024-04-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rarity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rarity',
            new_name='History',
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date']},
        ),
    ]
