# Generated by Django 5.0.3 on 2024-04-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_cleaning_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='cleaning_products',
            field=models.ManyToManyField(to='main_app.cleaning_product'),
        ),
    ]
